click install app + installation os windows
massalabs/Thyra-Menu-Bar-App pull request #22
Opened 2023-01-05 09:00 UTC by B-Naoufal

2023-01-06 13:30 UTC, B-Naoufal commented on background_thyra_scripts.py
> +    CONST_CMD_THYRA = shutil.which("thyra-server") #"/Users/massa/go/bin/thyra-server" #app tested on my mac works only with hardcoded path to investigate
comment to be reviewed

2023-01-06 13:35 UTC, B-Naoufal commented on background_thyra_scripts.py
> +        return self.thyra.start(1,expected_output)
in the previous versions i've wrote the code which start thyra, but the issue is we dont know if thyra is really running and nothing can be checked in logs, i added the expected output argument, assuming that we already know the correct format of logs when thyra is running correctly , ad i use regex expression to parse and compare actual logs to expected ones, so we know that we have or not an unexpected behaviour; (for example if  the ports we are using are occupied, before this update we were unable to track the result of starting thyra from the application)

2023-01-06 13:38 UTC, B-Naoufal commented on path.py
> +import os
thyra application needs the $path variable to be stored somewhere , because the app itself cannot get it while running , for that i am using a hook file , script path.py which extract the variable $path and store it in .config/path.txt , we can use also a batch file , so i pushed the two  and we will choose later if we will keep just one

2023-01-06 13:39 UTC, B-Naoufal commented on test_thyra_app.py
dummy test to be updated when we have more features to test in the app

2023-01-06 13:40 UTC, B-Naoufal commented on thyra_app.py
> +        if getattr(sys, 'frozen', False):
when we run the app it export the ressources to a temporary folder which can be retrieved using MEIPASS, otherwise , the app will not work.

2023-01-06 13:41 UTC, B-Naoufal commented on thyra_app.py
> +        log_file = os.path.join(self.config_dir, 'ThyraApp.log')
to track the behaviour of the app, a log file is stored in .config with all logs.

2023-01-09 09:22 UTC, ASAPSegfault requested changes
I tested on Windows with Thyra already installed and the app works fine, I will delete thyra from my computer, relaunch the script and check that everything is working fine and that log/conf files are properly generated.

2023-01-09 09:22 UTC, ASAPSegfault commented on thyra_app.py
> +        if file_path:
Shouldn't we print an error if this fails ? Because if we let this as is, the app may not work and the user won't know why.

2023-01-09 09:22 UTC, ASAPSegfault commented on thyra_app.py
>              # Add the "Start Thyra" action if there-server is installed
```suggestion
            # Add the "Start Thyra" action if thyra-server is installed
```

2023-01-09 09:22 UTC, ASAPSegfault commented on .github/workflows/build.yml
> +      - name: Install dependencies
Shouldn't these dependencies installation rather take place in the action.yml file along with the other dependencies installation process ?

2023-01-09 13:56 UTC, ASAPSegfault approved these changes

2023-01-09 14:19 UTC, gregLibert approved these changes
:man_shrugging: LGTM

2023-01-09 14:20 UTC, merged