Deprecated "Path.txt"
massalabs/Thyra-Menu-Bar-App pull request #34
Opened 2023-02-06 20:57 UTC by B-Naoufal

2023-02-08 15:19 UTC, B-Naoufal commented
@SlnPons this Pull request should fix all issues related to thyraApp installation  in windows or any other os, including the "é" we faced with @SebastienValla  config.  @SebastienValla can you confirm please if it's the case, so we can merge it and publish a new release ?

2023-02-28 13:37 UTC, thomas-senechal requested changes

2023-02-28 13:37 UTC, thomas-senechal commented on thyra_app.py
> +            logging.error("cannot find thyra-server path.")
```suggestion
        thyra_server_path = os.path.join(self.home_dir, self.THYRA_SERVER_FILENAME)

        if not os.path.isfile(thyra_server_path):
            logging.error("cannot find thyra-server path.")
```

2023-02-28 13:37 UTC, thomas-senechal commented on thyra_app.py
> +            logging.info("The thyra-server is installed and will be launched from the path {}.".format(thyra_serer_path))
```suggestion
            logging.info("The thyra-server is installed and will be launched from the path {}.".format(thyra_server_path))
```

2023-02-28 13:37 UTC, thomas-senechal commented on utils/background_thyra_scripts.py
> +        "Connected to node server https://test.massa.net/api/v2 (version TEST.19.1)",
We are currently in 19.3. And next week, we should be in 20.0. I'm not sure we should keep that "expected output" check. It might be wrong depending on the plugins installed, the port used by the user to run Thyra...

If we really want to check that, we should use regexes to search for specific parterns that could come from an error I think. I think we should discuss about that to find the best solution, but for now, I think we shouldn't use this check.

2023-03-17 11:02 UTC, thomas-senechal approved these changes

2023-03-27 14:40 UTC, SebastienValla approved these changes
Nice !

2023-04-04 08:11 UTC, merged